### ISSUE TITLE
not able to run

### ISSUE THREAD

**Issue by Ratanr** [CodeAllNightTutorials/Handlebars.js-tutorial#1]
Hi,

I downloaded the package and ran the index file but I am not getting any results, its coming blank. could you please suggest why?

Thanks,
RR

**Comment by MarcelRobitaille** [comment]
When you say you "ran" it, did you run it in node? You have to open `index.html` in a browser. Also, check the console for errors.

**Comment by Ratanr** [comment]
Yes, I did run it and I got the below error

![image](https://user-images.githubusercontent.com/21287124/39398035-02310940-4ad6-11e8-83ff-e251950dd90d.png)

I believe, the steps **src="bower_components/handlebars/handlebars.js"** is not working for me, I downloaded the handlebars-v4.0.11.js package from the site and placed it in the folder. I saw you have done using **bower install -s handlebars** , this particular step is not working for me when I am doing using Command window.

Please suggest.

**Comment by MarcelRobitaille** [comment]
Did you run `bower install`?

**Comment by Ratanr** [comment]
I tried to run it but it is throwing the error, it is not able to recognize the keyword bower, please see below

![image](https://user-images.githubusercontent.com/21287124/39400167-20a0b81c-4af9-11e8-9fc9-aa6c046181d4.png)


DoI need to install any software before I run it using command window? what I did was I downloaded the handlebars-v4.0.11.js and placed it in work folder.

please let me know.

**Comment by MarcelRobitaille** [comment]
You have to install bower in order to use the command. You can also use a CDN link if you want such as `https://cdnjs.com/libraries/handlebars.js`.

**Comment by Ratanr** [comment]
I am not sure where I am doing wrong, I install the bower and then tried to run it and not able to succeed. I install bower but when I am running bower install -s handlebars, then it is not able to recognize and throwing the below error.


![image](https://user-images.githubusercontent.com/21287124/39401004-8d3737a2-4b09-11e8-9d01-9ea872c5b42f.png)

Thanks.

**Comment by MarcelRobitaille** [comment]
`npm` installed `bower` to `C:\Users\ratan\AppData\Roaming\npm\node_modules\bin\bower`. You have to make sure that `C:\Users\ratan\AppData\Roaming\npm\node_modules\bin\` is in your `$PATH` variable (or you can run bower using the whole path).

**Comment by Ratanr** [comment]
Ok, I think I am close.

I have changed the path to C:\Users\ratan\AppData\Roaming\npm and run the bower and it throws notification that GIt is not installed like this

**ENOGIT Git is not installed or not in the PATH**

then I installed GIT and run the bower command but it not showing any notification whether it got installed or not in that folder, instead, it is giving me an option to put an input like **? Answer**, I am not sure what to input here..

![image](https://user-images.githubusercontent.com/21287124/39401766-9914a11a-4b1b-11e8-9054-8ad1b458cfa6.png)

**Comment by Ratanr** [comment]
if you see in Screenshot, when I am using path**C:\Users\ratan>bower install -s handlebars**, I am not getting any notification but when I am using project folder path then I am getting an option to provide an answer.

Have you ever come across this scenario?

**Comment by MarcelRobitaille** [comment]
You said you *changed* the `$PATH` variable. You have to *append* to it as to not replace what's already there (i.e. git). Google "add to path windows" to find out how (I forget how to do it as I don't use windows).

**Comment by Ratanr** [comment]
ohh,

I was checking the console and found that i had not created the folder which we have defined in the script i.e **bower_components\handlebars**

I created it now and able to run.

Thank you for your help. I troubled you a lot today.

Have a great Sunday!

**Comment by MarcelRobitaille** [comment]
Thanks. You too buddy.
